AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM Template for ServerlessMicroserviceApp'


# ======================== GLOBAL ======================== #
Globals:
  Function:
    Runtime: python3.8
    Handler: app.lambda_handler
    Timeout: 60 # default is 3 seconds the function can run before it is stopped
    Environment:
      Variables:
        TABLE_NAME: !Ref ProductsTable

# ======================== RESOURCES API GATEWAY ======================== #
Resources:
  
  EcomApi: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  CreateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'CreateProductFunction'
      CodeUri: src/products/create
      Policies: # follow the principle of least privilege
        - DynamoDBCrudPolicy: # AWS SAM policy
            TableName: !Ref ProductsTable
        - AWSLambdaBasicExecutionRole
      Events:
        CreateProductApi:
          Type: Api
          Properties:
            RestApiId: !Ref EcomApi
            Path: /products
            Method: post

  GetProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'GetProductFunction'
      CodeUri: src/products/detail
      Policies: # follow the principle of least privilege
        - DynamoDBCrudPolicy: # AWS SAM policy
            TableName: !Ref ProductsTable
        - AWSLambdaBasicExecutionRole
      Events:
        CreateProductApi:
          Type: Api
          Properties:
            RestApiId: !Ref EcomApi
            Path: /product/{uuid}
            Method: get

  UpdateProductFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 'UpdateProductFunction'
      CodeUri: src/products/edit
      Policies: # follow the principle of least privilege
        - DynamoDBCrudPolicy: # AWS SAM policy
            TableName: !Ref ProductsTable
        - AWSLambdaBasicExecutionRole
      Events:
        CreateProductApi:
          Type: Api
          Properties:
            RestApiId: !Ref EcomApi
            Path: /product/{uuid}
            Method: put

  ProductsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: 'products-table'
      PrimaryKey:
        Name: uuid
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  Api:
    Description: 'API Gateway endpoint URL'
    Value: !Sub 'https://${EcomApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'