@hostname = xxxxxx.execute-api.ap-northeast-1.amazonaws.com/Prod/
@host = {{hostname}}

@uuid= xxxx

### Create Products
POST http://{{host}}/products HTTP/1.1
content-type: application/json

{
    "title" : "Banh Keo",
    "price" : 20000,
    "description" : "Test description"
}

### Get Product Details
GET http://{{host}}/product/{{uuid}} HTTP/1.1
content-type: application/json


### Update Product
PUT http://{{host}}/product/{{uuid}} HTTP/1.1
content-type: application/json

{
    "title" : "Banh Keo update",
    "price" : 25000,
    "description" : "Test update description"
}
